2022-04-21 15:30:59,118 INFO    MainThread:328255 [wandb_setup.py:_flush():71] setting env: {}
2022-04-21 15:30:59,119 INFO    MainThread:328255 [wandb_setup.py:_flush():71] setting login settings: {}
2022-04-21 15:30:59,119 INFO    MainThread:328255 [wandb_setup.py:_flush():71] setting login settings: {}
2022-04-21 15:30:59,119 INFO    MainThread:328255 [wandb_init.py:_log_setup():371] Logging user logs to /home/tbertrand/Bureau/ULM_4channel_pull/wandb/run-20220421_153059-178lppp8/logs/debug.log
2022-04-21 15:30:59,119 INFO    MainThread:328255 [wandb_init.py:_log_setup():372] Logging internal logs to /home/tbertrand/Bureau/ULM_4channel_pull/wandb/run-20220421_153059-178lppp8/logs/debug-internal.log
2022-04-21 15:30:59,119 INFO    MainThread:328255 [wandb_init.py:init():404] calling init triggers
2022-04-21 15:30:59,119 INFO    MainThread:328255 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-04-21 15:30:59,119 INFO    MainThread:328255 [wandb_init.py:init():460] starting backend
2022-04-21 15:30:59,119 INFO    MainThread:328255 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-21 15:30:59,125 INFO    MainThread:328255 [backend.py:ensure_launched():216] starting backend process...
2022-04-21 15:30:59,127 INFO    MainThread:328255 [backend.py:ensure_launched():221] started backend process with pid: 328374
2022-04-21 15:30:59,128 INFO    MainThread:328255 [wandb_init.py:init():469] backend started and connected
2022-04-21 15:30:59,130 INFO    MainThread:328255 [wandb_init.py:init():533] updated telemetry
2022-04-21 15:30:59,139 INFO    MainThread:328255 [wandb_init.py:init():563] communicating current version
2022-04-21 15:30:59,488 INFO    MainThread:328255 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.14 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-04-21 15:30:59,489 INFO    MainThread:328255 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-04-21 15:31:10,367 WARNING MainThread:328255 [wandb_init.py:init():952] interrupted
Traceback (most recent call last):
  File "/home/tbertrand/Bureau/ULM_4channel_pull/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/home/tbertrand/Bureau/ULM_4channel_pull/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 579, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/home/tbertrand/Bureau/ULM_4channel_pull/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 210, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/tbertrand/Bureau/ULM_4channel_pull/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 311, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/tbertrand/Bureau/ULM_4channel_pull/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/tbertrand/Bureau/ULM_4channel_pull/lib/python3.8/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/tbertrand/anaconda3/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/home/tbertrand/anaconda3/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
